const data = {
    "components":[{
        "type":"header",
        "components":[{
            "type":"div",
            "components":[{
                "type":"div"
            },{
                "type":"div"
            },{
                "type":"div"
            }]
        },{
            "type":"div",
            "components":[{
                "type":"div"
            },{
                "type":"div"
            },{
                "type":"div"
            },{
                "type":"div"
            }]
        },{
            "type":"div",
            "components":[{
                "type":"div"
            },{
                "type":"div"
            },{
                "type":"div"
            },{
                "type":"div"
            },{
                "type":"div"
            }]
        }]
    },{
        "type":"div",
        "components":[{
            "type":"div",
            "components":[{
                "type":"div"
            },{
                "type":"div"
            },{
                "type":"div"
            },{
                "type":"div"
            },{
                "type":"div"
            },{
                "type":"div"
            }]
        },{
            "type":"div",
            "components":[{
                "type":"div"
            },{
                "type":"div"
            },{
                "type":"div"
            },{
                "type":"div"
            },{
                "type":"div"
            },{
                "type":"div"
            }]
        },{
            "type":"div",
            "components":[{
                "type":"div"
            },{
                "type":"div"
            },{
                "type":"div"
            },{
                "type":"div"
            },{
                "type":"div"
            }]
        }]
    },{
        "type":"div",
        "components":[{
            "type":"div",
            "components":[{
                "type":"div"
            },{
                "type":"div"
            },{
                "type":"div"
            },{
                "type":"div"
            },{
                "type":"div"
            }]
        },{
            "type":"div",
            "components":[{
                "type":"div"
            },{
                "type":"div"
            },{
                "type":"div"
            },{
                "type":"div"
            },{
                "type":"div"
            }]
        },{
            "type":"div",
            "components":[{
                "type":"div",
                "components":[{
                    "type":"div"
                },
                {
                    "type":"button"
                },
                {
                    "type":"div"
                }]
            },{
                "type":"div"
            },{
                "type":"div"
            },{
                "type":"div"
            },{
                "type":"div"
            },{
                "type":"div"
            }]
        },{
            "type":"div",
            "components":[{
                "type":"div"
            },{
                "type":"div"
            },{
                "type":"div"
            },{
                "type":"div"
            },{
                "type":"div"
            },{
                "type":"div"
            }]
        }]
    }]
}
